name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        description: a cheerful word
        required: true
        default: Hello
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}, はろー"
      - uses: actions/checkout@v4