name: Secrets
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        env:
            PASSWORD: ${{ secrets.PASSWORD }}
        steps:
            - name: Print Secret
              run: |
                echo "${PASSWORD}"
                echo "${PASSWORD:0:1} ${PASSWORD:#?}"